[package]
name = "redwood"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.32.2"
glutin-winit = "0.5.0"
rand = "0.9.0"
skia-safe = { version = "0.84.0", features = ["gl"] } 
winit = "0.30.9"
gl-rs = { version = "0.14.0", package = "gl" }